services:
  backend:
    command: php artisan serve --host=0.0.0.0 --port=8000
    ports:
    - container: 8000
      http: 8000
    dockerfile: Dockerfile
    tags:
    - cloud66.sourdough
    build_root: ''
    dockerfile_path: Dockerfile
    git_url: git@github.com:jin-cloud66/koel.git
    git_branch: master
    build_vars: {}
  frontend:
    command: yarn hot
    ports:
    - container: 8080
      http: 8080
    git_url: git@github.com:jin-cloud66/koel.git
    git_branch: master
    dockerfile: Dockerfile
    tags:
    - cloud66.sourdough
